name: Build and Lint Next.js App

# Trigger the workflow on push to the main branch or on pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKER_REGISTRY: registry.hub.docker.com/filbary
  IMAGE_NAME: nextjs-test
  AZURE_APP: firstnextjs

jobs:
  # Job for setting up Node.js, installing dependencies, linting, and building the app
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '23'  # Use the Node.js version you need for your project
        
    - name: Install dependencies
      run: make install

    - name: Run Linters
      run: make check  # Add a linting step to check code style, etc.
  
  docker:
    needs: lint
    runs-on: ubuntu-latest  # Specify the runner for the Docker job
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: |
          ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy:
    needs: docker
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_APP }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}